---
DNS1:
  192.168.1.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "pihole.home"

env:
  - name: WEBPASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: WEBPASSWORD

serviceWeb:
  loadBalancerIP: 192.168.5.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.5.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
