---
DNS1: 
  192.168.1.1
persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.5.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.5.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
