repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  #Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.8.0
    values:
       - ./values/longhorn.values.yaml

  #Load Balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.9
  
  #Pi Hole
  - name: pihole
    chart: mojo2600/pihole
    namespace: pihole-system
    version: 2.27.0
    values: 
      - ./values/pihole.values.yaml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.12.0
    values:
      - ./values/nginx-internal.values.yaml

  # Automatic DNS
  - name: externaldns-pihole
    chart: bitnami/external-dns
    namespace: pihole-system
    version: 8.7.6
    values:
      - ./values/externaldns.values.yaml
     
  # Homepage Dashboard
  - name: homepage
    namespace: homepage-system
    chart: ./charts/homepage
    values:
      - ./values/homepage.values.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.0
    # Install CRDs if they are not already installed
    values:
      - crds: enabled
